name=hybx_vl53l5cx
version=0.1.0
author=Dale Weber <dale@hybridrobotix.io>
maintainer=Dale Weber <dale@hybridrobotix.io>
sentence=Minimal heap-free VL53L5CX ToF sensor library for Arduino UNO Q / Zephyr RTOS.
category=Sensors
url=https://github.com/hybotix/hybx_vl53l5cx
architectures=*
